
development:
  adapter: postgresql
  encoding: unicode
  database: sample_app_dev2
  pool: 5
  username: sample_app
  password: rail$i$gr3at!
  host: localhost
  Port: 5432

test: &test
  adapter: postgresql
  encoding: unicode
  database: sample_app_test2
  pool: 5
  username: sample_app
  password: rail$i$gr3at!
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: sample_app_production2
  pool: 5
  username: sample_app
  password:

cucumber:
  <<: *test